### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by karlkovaciny** [mandiberg/Names-Surnames-and-Countries-for-Stopwords#1]
This looks useful. Would you consider adding a license so others can use it?

On the need for a license: 
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Choosing a license:
http://choosealicense.com/ 

Example of adding an MIT license:
https://github.com/louisukiri/SlackClient/pull/5

**Comment by mandiberg** [comment]
done. sorry. thanks for pointing that out

M

ᐧ
